"""add table wbs detail

Revision ID: 3cb03990feb3
Revises: e313e65208ff
Create Date: 2023-07-16 15:39:39.395925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb03990feb3'
down_revision = 'e313e65208ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbs_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wbs_header_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wbs_header_id'], ['wbs_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wbs_detail')
    # ### end Alembic commands ###
