"""remove relation between project and sheet name

Revision ID: 3d6d54e2f1b3
Revises: 7ea7702297da
Create Date: 2023-07-16 08:02:09.120361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d6d54e2f1b3'
down_revision = '7ea7702297da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_name', schema=None) as batch_op:
        batch_op.drop_constraint('sheet_name_ibfk_1', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sheet_name_ibfk_1', 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###
