"""add column revit excel and photo file size

Revision ID: 7ea7702297da
Revises: cee4e329ed51
Create Date: 2023-07-16 07:17:46.428447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea7702297da'
down_revision = 'cee4e329ed51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revit_file_size', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('excel_file_size', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('photo_file_size', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('photo_file_size')
        batch_op.drop_column('excel_file_size')
        batch_op.drop_column('revit_file_size')

    # ### end Alembic commands ###
