"""alter column created at updated at table wbs header detail item project

Revision ID: 904f4b482194
Revises: 25a1ef708a3c
Create Date: 2023-07-23 10:40:40.499818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '904f4b482194'
down_revision = '25a1ef708a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wbs_detail_project', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('wbs_header_project', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('wbs_item_project', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wbs_item_project', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('wbs_header_project', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('wbs_detail_project', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
