"""add table wbs item

Revision ID: bdde19de8124
Revises: f1033f042e9d
Create Date: 2023-07-16 17:22:50.632819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdde19de8124'
down_revision = 'f1033f042e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbs_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wbs_detail_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wbs_detail_id'], ['wbs_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wbs_item')
    # ### end Alembic commands ###
