"""add column code to wbs detail table

Revision ID: f1033f042e9d
Revises: 3cb03990feb3
Create Date: 2023-07-16 15:58:16.338197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1033f042e9d'
down_revision = '3cb03990feb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wbs_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wbs_detail', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
